export const tiposTareas = {
  BUSCAR_TAREAS_PENDIENTE: 'BUSCAR_TAREAS_PENDIENTE',
  BUSCAR_TAREAS_TERMINADA: 'BUSCAR_TAREAS_TERMINADA',
  BUSCAR_TAREAS_RECHAZADA: 'BUSCAR_TAREAS_RECHAZADA',
  NUEVA_TAREA: 'NUEVA_TAREA',
  GUARDAR_TAREA: 'GUARDAR_TAREA',
  BUSCAR_TAREAS_POR_ID_PENDIENTE: 'BUSCAR_TAREAS_POR_ID_PENDIENTE',
  BUSCAR_TAREAS_POR_ID_TERMINADA: 'BUSCAR_TAREAS_POR_ID_TERMINADA',
  BUSCAR_TAREAS_POR_ID_RECHAZADA: 'BUSCAR_TAREAS_POR_ID_RECHAZADA',
  ACTUALIZAR_TAREA: 'ACTUALIZAR_TAREA',
  ELIMINAR_TAREA: 'ELIMINAR_TAREA',
};


export const tiposProductos = {
  BUSCAR_PRODUCTOS_PENDIENTE: 'BUSCAR_PRODUCTOS_PENDIENTE',
  BUSCAR_PRODUCTOS_TERMINADA: 'BUSCAR_PRODUCTOS_TERMINADA',
  BUSCAR_PRODUCTOS_RECHAZADA: 'BUSCAR_PRODUCTOS_RECHAZADA',
  NUEVO_PRODUCTO: 'NUEVO_PRODUCTO',
  GUARDAR_PRODUCTO: 'GUARDAR_PRODUCTO',
  BUSCAR_PRODUCTOS_POR_ID_PENDIENTE: 'BUSCAR_PRODUCTOS_POR_ID_PENDIENTE',
  BUSCAR_PRODUCTOS_POR_ID_TERMINADA: 'BUSCAR_PRODUCTOS_POR_ID_TERMINADA',
  BUSCAR_PRODUCTOS_POR_ID_RECHAZADA: 'BUSCAR_PRODUCTOS_POR_ID_RECHAZADA',
  ACTUALIZAR_PRODUCTO: 'ACTUALIZAR_PRODUCTO',
  ELIMINAR_PRODUCTO: 'ELIMINAR_PRODUCTO'

};

export const tiposServicios = {
  BUSCAR_SERVICIOS_PENDIENTE: 'BUSCAR_SERVICIOS_PENDIENTE',
  BUSCAR_SERVICIOS_TERMINADA: 'BUSCAR_SERVICIOS_TERMINADA',
  BUSCAR_SERVICIOS_RECHAZADA: 'BUSCAR_SERVICIOS_RECHAZADA',
  NUEVO_SERVICIO: 'NUEVO_SERVICIO',
  GUARDAR_SERVICIO: 'GUARDAR_SERVICIO',
  BUSCAR_SERVICIOS_POR_ID_PENDIENTE: 'BUSCAR_SERVICIOS_POR_ID_PENDIENTE',
  BUSCAR_SERVICIOS_POR_ID_TERMINADA: 'BUSCAR_SERVICIOS_POR_ID_TERMINADA',
  BUSCAR_SERVICIOS_POR_ID_RECHAZADA: 'BUSCAR_SERVICIOS_POR_ID_RECHAZADA',
  ACTUALIZAR_SERVICIO: 'ACTUALIZAR_SERVICIO',
  ELIMINAR_SERVICIO: 'ELIMINAR_SERVICIO'
}



